"""add inventory management fields to ticket_types

Revision ID: 097cf5b54a65
Revises: 34eef9b0ba0d
Create Date: 2026-01-08 01:51:55.525266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097cf5b54a65'
down_revision: Union[str, None] = '34eef9b0ba0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_types', sa.Column('available_quantity', sa.Integer(), nullable=True))
    op.add_column('ticket_types', sa.Column('sold_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_types', 'sold_quantity')
    op.drop_column('ticket_types', 'available_quantity')
    # ### end Alembic commands ###
