"""add qr code and validation fields to tickets

Revision ID: 34eef9b0ba0d
Revises: 9ca2ef198515
Create Date: 2026-01-08 01:50:28.356842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34eef9b0ba0d'
down_revision: Union[str, None] = '9ca2ef198515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('qr_code_data', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('validated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['validated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'validated_by')
    op.drop_column('tickets', 'validated_at')
    op.drop_column('tickets', 'qr_code_data')
    # ### end Alembic commands ###
