"""initial schema

Revision ID: b8e5e43b379d
Revises: 
Create Date: 2026-01-08 01:22:13.915669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8e5e43b379d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_description', table_name='events')
    op.drop_index('ix_events_event_name', table_name='events')
    op.drop_index('ix_events_image', table_name='events')
    op.drop_index('ix_events_location', table_name='events')
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.drop_index('ix_orders_payment_method', table_name='orders')
    op.drop_index('ix_orders_total_price', table_name='orders')
    op.create_index(op.f('ix_orders_event_id'), 'orders', ['event_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_index('ix_ticket_types_description', table_name='ticket_types')
    op.drop_index('ix_ticket_types_name', table_name='ticket_types')
    op.drop_index('ix_ticket_types_price', table_name='ticket_types')
    op.drop_index('ix_ticket_types_quantity', table_name='ticket_types')
    op.create_index(op.f('ix_ticket_types_event_id'), 'ticket_types', ['event_id'], unique=False)
    op.drop_index('ix_tickets_seat_number', table_name='tickets')
    op.drop_index('ix_tickets_qr_code', table_name='tickets')
    op.create_index(op.f('ix_tickets_qr_code'), 'tickets', ['qr_code'], unique=True)
    op.create_index(op.f('ix_tickets_order_id'), 'tickets', ['order_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_type_id'), 'tickets', ['ticket_type_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_users_firstname', table_name='users')
    op.drop_index('ix_users_password', table_name='users')
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_index('ix_users_street_address', table_name='users')
    op.drop_index('ix_users_surname', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_surname', 'users', ['surname'], unique=False)
    op.create_index('ix_users_street_address', 'users', ['street_address'], unique=False)
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=False)
    op.create_index('ix_users_password', 'users', ['password'], unique=False)
    op.create_index('ix_users_firstname', 'users', ['firstname'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_tickets_ticket_type_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_order_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_qr_code'), table_name='tickets')
    op.create_index('ix_tickets_qr_code', 'tickets', ['qr_code'], unique=False)
    op.create_index('ix_tickets_seat_number', 'tickets', ['seat_number'], unique=False)
    op.drop_index(op.f('ix_ticket_types_event_id'), table_name='ticket_types')
    op.create_index('ix_ticket_types_quantity', 'ticket_types', ['quantity'], unique=False)
    op.create_index('ix_ticket_types_price', 'ticket_types', ['price'], unique=False)
    op.create_index('ix_ticket_types_name', 'ticket_types', ['name'], unique=False)
    op.create_index('ix_ticket_types_description', 'ticket_types', ['description'], unique=False)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_event_id'), table_name='orders')
    op.create_index('ix_orders_total_price', 'orders', ['total_price'], unique=False)
    op.create_index('ix_orders_payment_method', 'orders', ['payment_method'], unique=False)
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.create_index('ix_events_location', 'events', ['location'], unique=False)
    op.create_index('ix_events_image', 'events', ['image'], unique=False)
    op.create_index('ix_events_event_name', 'events', ['event_name'], unique=False)
    op.create_index('ix_events_description', 'events', ['description'], unique=False)
    # ### end Alembic commands ###
